
defaults:
  - _self_
  - predictor: bnn.yaml 
  - optimizer: default.yaml
  - scheduler: default.yaml

_target_: uq4dd.model.bayesian_learning.BayesDTI
n_predictors: 500
n_experiments: ${n_experiments}
n_train_batches: ${n_train_batches}
uncertainty: 'bnn' 
recalibrate: 'none'
save_path: True
ckpt_path: null

drug_features: ${db.descriptors.fpSize}
censored: ${db.censored}
objective: ${db.objective}

