
defaults:
  - _self_
  - predictor: mve.yaml 
  - optimizer: default.yaml
  - scheduler: default.yaml

_target_: uq4dd.model.deep_learning.DeepDTI
n_predictors: 5
n_experiments: ${n_experiments}
uncertainty: 'gmm' 
recalibrate: 'none'
save_path: True
ckpt_path: null

drug_features: ${db.descriptors.fpSize}
censored: ${db.censored}
objective: ${db.objective}
  
