_target_: uq4dd.model.predictor.prf.PRF
objective: ${model.objective}
uncertainty: ${model.uncertainty}

n_estimators: 250         
max_depth: 1            

name: PRF
max_features: 'auto'  #default sqrt
use_py_gini: True
use_py_leafs: True
keep_proba: 0.05
bootstrap: True
min_py_sum_leaf: 1
n_jobs: -1
criterion: 'gini'
