
_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1
max_epochs: 500   # Should be 1 for baselines, and e.g. 500 for MLPs

accelerator: gpu  # Crutiallly cpu for baselines, gpu for MLPs
devices: "auto"

# mixed precision for extra speed-up
# precision: 16
#gradient_clip_val: 1

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1
log_every_n_steps: 50   # Should be 1 for baselines, and e.g. 50 for MLPs

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

fast_dev_run: ${debug}
num_sanity_val_steps: 2   # Should be 0 for baselines, 2 for MLPs

#profiler: simple

