
defaults: 
  - _self_                
  - hydra: default.yaml   # Ignore
  - paths: default.yaml   # Ignore
  - model: mlp.yaml       # Model configs, specify with argument e.g. model=mlp or model=ensemble
  - db: lipo.yaml         # Data configs, specify with argument e.g. db=lipo for regression or db=cyp3a4 for classification
  - trainer: torch.yaml   # Torch trainer configs for MLPs
  - logger: null          # No logging needed for pretraining
  - callbacks: base.yaml  # Simple callbacks, only early stopping and checkpointing for pretraining

# Information
name: ${db.dataset}_${now:%Y-%m-%d}_${now:%H-%M-%S}
project: UQ4DD
version: 0.0.1
description: "Uncertainty quantification for drug discovery."

# Training
seed: null
train: True             
test: False             # Optional testing during pretraining
cv: False
n_experiments: 1        # Note, has to be 1 for pretraining of MLPs
ckpt_path: null
ckpt_metric: loss
debug: False

batch_size: 256          # Batch size for training
batch_size_eval: 256     # Batch size for evaluation 
n_train_batches: null   # Gets infered after the datamodule is created

