
defaults: 
  - _self_                
  - hydra: default.yaml   # Ignore
  - paths: default.yaml   # Ignore
  - model: mlp.yaml       # Model configs, specify with argument e.g. model=mlp or model=ensemble
  - db: lipo.yaml         # Data configs, specify with argument e.g. db=lipo for regression or db=cyp3a4 for classification
  - trainer: torch.yaml   # Specify torch.yaml or sklearn trainer configs to match base estimator
  - logger: null          # Specify Wandb user to log sweep
  - callbacks: sweep.yaml # Simplest callback option with only early stopping

# Information
name: ${db.dataset}_${now:%Y-%m-%d}_${now:%H-%M-%S}
project: UQ4DD
version: 0.0.1
description: "Uncertainty quantification for drug discovery."

# Training
seed: null
train: True             
test: False             # No testing needed during sweeps
cv: False
n_experiments: 1        # Note, sweeps can only be performed with 1 experiments
ckpt_path: null
ckpt_metric: loss
debug: False

batch_size: 256         # Needs to be -1 for baselines and e.g. 64 for MLPs
batch_size_eval: 256    # Needs to be -1 for baselines and e.g. 64 for MLPs
n_train_batches: null   # Gets infered after the datamodule is created

